name: Update Flux

on:
  workflow_call:
    inputs:
      gotk-components-file:
        description: "gotk-components.yaml location"
        default: "./flux-system/gotk-components.yaml"
        required: false
        type: string
      author-name:
        description: "Commit Author email"
        default: ""
        required: true
        type: string
      author-email:
        description: "Commit Author email"
        default: ""
        required: true
        type: string
    secrets:
      app_id:
        description: "App ID of the application used to generate a token"
        required: true
      app_private_key:
        description: "Private key of the application used to generate a token"
        required: true

jobs:
  flux:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: "${{ secrets.app_id }}"
          private_key: "${{ secrets.app_private_key }}"

      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          token: "${{ steps.generate-token.outputs.token }}"

      - name: Update Flux components
        id: update
        run: |
          UGLY_VERSION="$(flux -v)"
          VERSION="v${UGLY_VERSION#*flux version }"
          flux install --version="${VERSION}" \
            --export > ${{ inputs.gotk-components-file }}
          echo "flux_version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create pull request for Flux update
        uses: peter-evans/create-pull-request@v7
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          branch: "flux/update-${{ steps.update.outputs.flux_version }}"
          delete-branch: true
          title: "chore(deps): update flux components to ${{ steps.update.outputs.flux_version }}"
          signoff: true
          committer: "${{ inputs.author-name }} <${{ inputs.author-email }}>"
          author: "${{ inputs.author-name }} <${{ inputs.author-email }}>"
          commit-message: "chore(deps): update flux components to ${{ steps.update.outputs.flux_version }}"
          body: |
            Release notes: https://github.com/fluxcd/flux2/releases/tag/${{ steps.update.outputs.flux_version }}
          labels: flux/update
