---
name: "Sync labels"

on:
  workflow_call:
    inputs:
      config-file:
        description: "Label configuration file"
        default: ".github/labels.yaml"
        required: false
        type: string
      delete-other-labels:
        description: "Delete other labels on sync"
        default: false
        required: false
        type: boolean
    secrets:
      app_id:
        description: "App ID of the application used to generate a token"
        required: true
      app_private_key:
        description: "Private key of the application used to generate a token"
        required: true

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: "${{ secrets.app_id }}"
          private_key: "${{ secrets.app_private_key }}"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: "${{ steps.generate-token.outputs.token }}"

      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: ${{ inputs.config-file }}
          token: "${{ steps.generate-token.outputs.token }}"
          delete-other-labels: ${{ inputs.delete-other-labels }}
